export const MAX_HAND_SIZE = 3;
export const MIN_SUBMISSION_SIZE = 4;

export const categories = [
    'Dogs',
    'Cats',
    'Old People',
    'Fruit',
    'My childhood',
    'Pillow Talk',
    'What I do when I\'m home alone',
    'Dad jokes',
    'Reasons to worry',
    'Sadness',
];

export const phrases = [
    'Coldplay',
    'Taking the hobbits to Isengard',
    'Two birds with one stone',
    'We will cross that bridge when we get to it',
    'Guns and Roses',
    'Dungeons and Dragons',
    'Another one bites the dust',
    'Bill Nye the science guy',
    'Hit the road Jack',
    'Jack and Jill went up the hill',
    'All night long',
    '28 days later',
    'Call me maybe',
    'Abraham Lincoln',
    'Barack Obama',
    'Twilight Zone',
    'One Direction',
    'Sammie Rae and the Friends',
    'Lean on Me',
    'A blessing in disguise',
    'A dime a dozen',
    'Beat around the bush',
    'Better late than never',
    'Bite the bullet',
    'Break a leg',
    'Call it a day',
    'Cut somebody some slack',
    'Cutting corners',
    'Easy does it',
    'Get out of hand',
    'Get something out of your system',
    'Get your act together',
    'Give someone the benefit of the doubt',
    'Go back to the drawing board',
    'No pain, no gain',
    'The best of both worlds',
];